# Generated by Django 4.2 on 2023-04-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
